server {
    listen 80 default_server;
    listen [::]:80 default_server ipv6only=on;
    server_name _;
    location /.well-known/acme-challenge/ {
        root /var/www/letsencrypt/;
        log_not_found off;
        allow all;
        default_type "text/plain";
        autoindex on;
    }
    location / {
        return 301 https://$host$request_uri;
    }
}

map $http_upgrade $type {
  default "web";
}

server {
    # For https
    listen 443 ssl default_server;
    listen [::]:443 ssl default_server ipv6only=on;
    ssl_certificate /var/certs/cert.pem;
    ssl_certificate_key /var/certs/privkey.pem;
    server_name _;
    root /var/www/public;
    index index.html index.htm index.php;

    # 1. Force Nginx to serve assets directly from disk
    location ~ ^/vendor/ {
        try_files $uri =404;
    }
    location ~ ^/storage/ {
        try_files $uri =404;
    }

    # 2. General Static File Handler
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # 3. Dedicated PHP-FPM Handler
    # Only executes requests ending in .php
    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_pass php-upstream;
        fastcgi_index index.php;
        fastcgi_buffers 16 16k;
        fastcgi_buffer_size 32k;
        fastcgi_param SCRIPT_FILENAME /var/www/public/$fastcgi_script_name;
        fastcgi_read_timeout 600;
        include fastcgi_params;
    }

    location ~ /\.ht {
        deny all;
    }

    location /.well-known/acme-challenge/ {
        root /var/www/letsencrypt/;
        log_not_found off;
    }
}
